# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "elements", :force => true do |t|
    t.column "data", :string
  end

  create_table "handles", :force => true do |t|
    t.column "name", :string
    t.column "node_id", :integer
    t.column "policy", :string
  end

  create_table "node_elements", :force => true do |t|
    t.column "node_id", :integer
    t.column "element_id", :integer
    t.column "order", :integer
  end

  create_table "nodes", :force => true do |t|
    t.column "hash", :text
    t.column "updated_at", :datetime
  end

  create_table "parents", :force => true do |t|
    t.column "parent_id", :integer
    t.column "child_id", :integer
  end

end
